sudo: required
services:
  - docker
script:
  - docker build -t infiniteproject/icecast .
  - docker run -d -p 8000:8000 -e ICECAST_ADMIN_PASSWORD=test -e ICECAST_SOURCE_PASSWORD=test infiniteproject/icecast
